title: Zhaole's Personal Web  # your title
author: Sun Zhaole # your name
description: A web for sharing Zhaole's academic career # your description
avatar: /images/Ichijou.png # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]

# Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics
